---
deployment:
  tasks:
    - /usr/local/bin/php /home/judoklub/repositories/judo-klub-bura/artisan config:clear
    - /usr/local/bin/php /home/judoklub/repositories/judo-klub-bura/artisan migrate --force
    - /usr/local/bin/php /home/judoklub/repositories/judo-klub-bura/artisan db:seed --class=AdminSeeder --force
    - /bin/rm -rf /home/judoklub/public_html/build
    - /bin/cp -r /home/judoklub/repositories/judo-klub-bura/public/build /home/judoklub/public_html/build
    - /bin/rm -rf /home/judoklub/public_html/images
    - /bin/cp -r /home/judoklub/repositories/judo-klub-bura/public/images /home/judoklub/public_html/images
    - /bin/cp -f /home/judoklub/repositories/judo-klub-bura/public/favicon.ico /home/judoklub/public_html/
    - /bin/cp -f /home/judoklub/repositories/judo-klub-bura/public/favicon.svg /home/judoklub/public_html/
    - /bin/cp -f /home/judoklub/repositories/judo-klub-bura/public/robots.txt /home/judoklub/public_html/
    - /bin/cp -f /home/judoklub/repositories/judo-klub-bura/public/apple-touch-icon.png /home/judoklub/public_html/
    - /bin/mkdir -p /home/judoklub/public_html/storage
