---
deployment:
  tasks:
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
    - rsync -a --exclude='index.php' /home/judoklub/repositories/judo-klub-bura/public/ /home/judoklub/public_html/
    - ln -sfn /home/judoklub/repositories/judo-klub-bura/storage/app/public /home/judoklub/public_html/storage
